services:
  vocab_bot:
    image: krishnaraj/vocab-bot:latest
    container_name: vocab_bot
    environment:
      - TOKEN=your_bot_token_here
      - CHAT_ID=your_chat_id_here
    volumes:
      - ./vocab.db:/app/vocab.db
    restart: unless-stopped

  word_importer:
    image: krishnaraj/vocab-bot:latest
    container_name: vocab_importer
    command: ["python", "import_words.py"]
    volumes:
      - ./vocab.db:/app/vocab.db
      - ./words.csv:/app/words.csv
    depends_on:
      - vocab_bot
