apiVersion: v1
kind: Service
metadata:
  name: vocabuildary
  namespace: vocabuildary
spec:
  type: NodePort
  selector:
    app: vocabuildary
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32013
